### ISSUE TITLE
Missing nuget.exe from pre-requisites

### ISSUE THREAD

**Issue by blahDL** [jfrog/nuget-deps-tree#14]
When running this on windows I was getting the folllowing output:
```
'locals' is not recognized as an internal or external command,
operable program or batch file.
{
  "projects": []
}
```
After much digging I found this was caused because I do not have `nuget.exe` available in any of the path locations

When you don't find mono or nuget on non-windows environments you display an error message saying what is missing, but there isn't anything similar for windows environments

It would probably be a good idea to list `nuget.exe` as a pre-requisite in the readme and it wouldn't hurt to add an error message similar to the non-windows environments.

Also of note is that `nuget.exe` is itself is not included with any version of Visual Studio and has to be downloded from https://www.nuget.org/downloads

**Comment by eyalbe4** [comment]
Thanks for sharing and reporting this @blahDL. 
Would you like to create a pull request to add this to the README?

**Comment by RobiNino** [comment]
Hi @blahDL ,
A prerequisites section was added to README.md.
Thanks for the feedback
